repos:
  - repo: local
    hooks:
      - id: nix flake check
        name: Lint with nix flake check.
        language: system
        entry: nix flake check
        pass_filenames: false
      - id: statix-check
        name: Lint with statix.
        language: script
        entry: ./scripts/statix-check.sh
        pass_filenames: false
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        name: Lint with ansible-lint.
