---
- name: Install flatpaks.
  hosts: localhost
  tasks:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
    - name: Install flatpaks.
      community.general.flatpak:
        method: user
        remote: flathub
        name:
          - com.axosoft.GitKraken
          - com.discordapp.Discord
          - com.microsoft.Edge
          - com.spotify.Client
          - com.valvesoftware.Steam
          - md.obsidian.Obsidian
          - org.fkoehler.KTailctl
          - org.onlyoffice.desktopeditors
          - us.zoom.Zoom
