---
- name: Install flatpaks.
  hosts: localhost
  tasks:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
    - name: Install flatpaks.
      community.general.flatpak:
        method: user
        remote: flathub
        name:
          - ch.protonmail.protonmail-bridge
          - com.bitwarden.desktop
          - com.discordapp.Discord
          - com.github.iwalton3.jellyfin-media-player
          - com.microsoft.Edge
          - com.spotify.Client
          - com.valvesoftware.Steam
          - md.obsidian.Obsidian
          - org.fkoehler.KTailctl
          - org.gimp.GIMP
          - org.inkscape.Inkscape
          - org.libreoffice.LibreOffice
          - org.mozilla.Thunderbird
          - org.mozilla.firefox
          - org.telegram.desktop
          - org.videolan.VLC
          - org.zotero.Zotero
          - us.zoom.Zoom
