version: "3.8"
services:
  gotenberg:
    image: "docker.io/gotenberg/gotenberg:8.6.0"
    restart: unless-stopped
    environment:
      CHROMIUM_DISABLE_ROUTES: 1
    ports:
      - "3000:3000"
  # TODO: enable X86
  # tika:
  #   image: "docker.io/apache/tika:2.9.1.0-full"
  #   restart: unless-stopped
  #   links:
  #     - gotenberg
