- name: Configure KDE Plasma.
  hosts: localhost
  tasks:
    - name: Create config directory.
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
        mode: "0755"
    - name: Render templates.
      ansible.builtin.template:
        src: "templates/{{ file }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ file }}"
        mode: "0644"
      loop_control:
        loop_var: file
      loop:
        - ktimezonedrc
        - plasma-localerc
        - kwinrulesrc
        - kactivitymanagerdrc
