- name: Configure KDE Plasma.
  hosts: localhost
  tasks:
    - name: Render templates.
      ansible.builtin.template:
        src: "templates/{{ file }}"
        dest: "~/.config/{{ file }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: "0644"
      loop_control:
        loop_var: file
      loop:
        - ktimezonedrc
        - plasma-localerc
        - kwinrulesrc
        - kactivitymanagerdrc
