name: "Lint"
on:
  pull_request:
  push:
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check main flake
        run: nix flake check
      - name: Check nix-darwin flake
        run: nix flake check
        working-directory: nix-darwin
  nixpkgs-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Format
        run: ./scripts/nixpkgs-fmt.sh
  statix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint
        run: ./scripts/statix-check.sh
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
  home-manager:
    runs-on: ubuntu-latest
    needs:
      - nix-flake-check
      - nixpkgs-fmt
      - statix
      - deadnix
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Create state directory.
        run: mkdir -p ~/.local/state/nix/profiles
      - name: Run home-manager.
        run: nix run home-manager/master -- switch -b backup --flake ".#runner"
