name: "Lint"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check flake
        run: nix flake check
  nixpkgs-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Format
        run: ./scripts/nixpkgs-fmt.sh
  statix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint
        run: ./scripts/statix-check.sh
  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
  flake-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/flake-checker-action@v5
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "ansible-galaxy install -r requirements.yml && ansible-lint ." -p ansible ansible-lint
        working-directory: plasma
  home-manager:
    runs-on: ubuntu-latest
    needs:
      - nix-flake-check
      - nixpkgs-fmt
      - statix
      - deadnix
      - flake-checker
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Create state directory.
        run: mkdir -p ~/.local/state/nix/profiles
      - name: Run home-manager.
        run: nix run home-manager/master -- switch -b backup --flake ".#gha"
  ansible:
    runs-on: ubuntu-latest
    needs:
      - ansible-lint
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install flatpak.
        run: sudo apt install flatpak gsettings-desktop-schemas
      - name: Deploy
        run: nix-shell --run "ansible-galaxy install -r requirements.yml && ansible-playbook plasma.yml" -p ansible libsForQt5.kconfig
        working-directory: plasma
